#!/usr/bin/env python3
"""Build the offline browser library from the curated, attributed lesson records."""
import json
import hashlib
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
starters = json.loads((ROOT / 'content/starter-lessons.json').read_text())
extras = json.loads((ROOT / 'content/source-exercises.json').read_text())
extras += json.loads((ROOT / 'content/long-exercises.json').read_text())
lessons = {track: [] for track in starters}
for record in extras:
    meta = {k: v for k, v in record.items() if k not in ('track', 'title', 'text')}
    lessons[record['track']].append([record['title'], record['text'], meta])
for track, rows in starters.items():
    for title, text in rows:
        kind = title.split(' · ')[0] if track != 'Foundations' else 'Foundations'
        lessons[track].append([title, text, {'kind': kind, 'source': 'Typewell original practice', 'provenance': 'Original exercise', 'note': 'Authored typing practice; not quoted from a test question.'}])
seen = set()
for track, rows in lessons.items():
    for title, text, meta in rows:
        assert (track, title) not in seen, (track, title)
        seen.add((track, title))
        meta['id'] = hashlib.sha256((track + '\0' + title + '\0' + text).encode()).hexdigest()[:24]
        assert text and len(text) <= 20000, title
        assert all(c == '\n' or ' ' <= c <= '~' for c in text), title
        assert '###' not in text and '<br' not in text and 'Correct Answer' not in text, title
        assert all(line == line.rstrip() for line in text.splitlines()), title
        assert meta['source'] and meta['note'] and meta['kind'], title
(ROOT / 'lessons.js').write_text('// Generated by scripts/build-lessons.py. Edit content/*.json, then rebuild.\nconst LESSONS = ' + json.dumps(lessons, ensure_ascii=False, indent=2) + ';\n')
print('Validated and built:', ', '.join(f'{k}: {len(v)}' for k, v in lessons.items()))

(ROOT / 'server/race-lessons.json').write_text(json.dumps({meta['id']: dict(id=meta['id'],track=track,title=title,text=text) for track, rows in lessons.items() for title,text,meta in rows},ensure_ascii=False,indent=2)+'\n')
